name: Test on Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14 # Use the appropriate Node.js version
          cache: "npm" # Caches node_modules for faster runs

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test:unit:ci

  e2e-test:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    needs: unit-test # Only run if unit tests pass

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm run build
        env:
          NODE_ENV: test

      - name: Start Application
        run: npm start
        env:
          NODE_ENV: test
        continue-on-error: true # Ensure Cypress runs even if start fails

      - name: Wait for Server to be Ready
        run: npx wait-on http://localhost:3000 # Adjust for your app's port

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          wait-on: http://localhost:3000 # Wait for server before running tests
          browser: chrome

      - name: Upload Cypress Screenshots (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Cypress Videos (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
